# Copyright 2026 Max Planck Institute for Software Systems,
# National University of Singapore, and SimBricks UG (haftungsbeschränkt)
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

{% set name = "simbricks-cli" %}

package:
  name: {{ name|lower }}
  version: {{ simbricks_version }}

source:
  path: ../../symphony/cli

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - simbricks-cli = simbricks.cli.__main__:main

requirements:
  host:
    - python >=3.10
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10
    - pydantic-settings 2.14.1
    - rich 15.0.0
    - typer 0.26.7
    - typing_extensions >=4.14.1
    - readchar 4.2.2
    - simbricks-client >=0.5.0
    - simbricks-orchestration >=0.5.0
    - simbricks-telemetry >=0.5.0
    - simbricks-utils >=0.5.0

test:
  imports:
    - simbricks.cli
  commands:
    - simbricks-cli --help

about:
  home: https://www.simbricks.io/
  license: MIT
  summary: SimBricks CLI tool for communication with the SimBricks backend
  dev_url: https://github.com/simbricks/simbricks

extra:
  recipe-maintainers:
    - Team SimBricks <team@simbricks.io>
