version: 2

submodules:
  exclude: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz 

sphinx:
  configuration: doc/conf.py

python:
   install:
   - requirements: doc/requirements.txt
