ARG REGISTRY=
ARG TAG=:latest
FROM ${REGISTRY}simbricks/simbricks${TAG}
USER root
RUN apt-get update \
 && apt-get install -y \
	openssh-server \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /run/sshd \
 && ssh-keygen -N '' -f ~/.ssh/id_rsa \
 && cat ~/.ssh/id_rsa.pub >~/.ssh/authorized_keys \
 && mkdir ~/.ssh/controls
COPY dist/ssh_config /etc/ssh/ssh_config.d/simbricks.conf
COPY dist/sshd_config /etc/ssh/sshd_config.d/simbricks.conf
CMD ["/usr/sbin/sshd","-D", "-p", "2222"]
