name: lint-cpplint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
    - run: |
        pip install cpplint
        make lint-cpplint
