name: lint-python

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-python:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: pip
    - run: pip install -r requirements.txt
    - run: make lint-python
