name: lint-clang-format

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-clang-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install clang-format
    - run: make lint-clang-format
